-- 1. USUARIOS (Analistas: Matías, Jorge, etc.)
CREATE TABLE USUARIOS (
    rut_analista VARCHAR2(10) NOT NULL, 
    nombre_apellido_analista VARCHAR2(100) NOT NULL,
    correo_analista VARCHAR2(100) NOT NULL,
    contrasena_analista VARCHAR2(100) NOT NULL,
    rol_analista NUMBER(1) DEFAULT 0,
    CONSTRAINT PK_usuarios PRIMARY KEY(rut_analista)
);

-- 2. LUGARES ALMACENAMIENTO (Ej: "Freezer 33-M")
CREATE TABLE LUGARES_ALMACENAMIENTO (
    id_lugar NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_lugar VARCHAR2(100) NOT NULL,
    codigo_lugar VARCHAR2(20)
);
    
    -- 3. INSTRUMENTOS (Manuales: Cucharas, Bisturís)
    CREATE TABLE INSTRUMENTOS (
        id_instrumento NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_instrumento VARCHAR2(100) NOT NULL,
        codigo_instrumento VARCHAR2(50)
    );
    
    -- 4. MICROPIPETAS (Recurso específico)
    CREATE TABLE MICROPIPETAS (
        id_pipeta NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_pipeta VARCHAR2(100) NOT NULL,
        codigo_pipeta VARCHAR2(50) NOT NULL,
        capacidad VARCHAR2(20) NOT NULL
    );
    
    -- 5. EQUIPOS DE LABORATORIO (Para selección múltiple en Etapa 2: Balanzas, Cámaras)
    CREATE TABLE EQUIPOS_LAB (
        id_equipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_equipo VARCHAR2(100) NOT NULL,
        codigo_equipo VARCHAR2(50)
    );
    
    -- 6. CATÁLOGOS PARA ETAPA 5 (SIEMBRA)
    CREATE TABLE MATERIAL_SIEMBRA (
        id_material_siembra NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_material VARCHAR2(100) NOT NULL, -- Ej: "Blender"
        detalle_medida VARCHAR2(100)
    );
    
    CREATE TABLE DILUYENTES (
        id_diluyente NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_diluyente VARCHAR2(100) NOT NULL, -- Ej: "PBS 450 ml"
        mililitros VARCHAR2(50) NOT NULL
    );
    
    CREATE TABLE EQUIPOS_INCUBACION (
        id_incubacion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_equipo VARCHAR2(100) NOT NULL, -- Ej: "Homogenizador 12-m"
        temperatura_ref VARCHAR2(50)
    );
    
    CREATE TABLE MAESTRO_CHECKLIST_LIMPIEZA (
        id_item NUMBER PRIMARY KEY,
        nombre_item VARCHAR2(100),
        def_seleccionado NUMBER(1), -- 1: true, 0: false (Valor por defecto)
        def_bloqueado NUMBER(1)     -- 1: true, 0: false (Valor por defecto)
    );
    
    CREATE TABLE MAESTRO_TIPOS_ANALISIS (
        id_tipo_analisis NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        nombre_analisis VARCHAR2(100)
    );
    
    -- C. Para getFormasCalculo()
    CREATE TABLE MAESTRO_FORMAS_CALCULO (
        id_forma NUMBER PRIMARY KEY,
        nombre_forma VARCHAR2(100),
        def_seleccionado NUMBER(1) -- 1: true, 0: false
    );
    
    
    
    --VISTA NORMAL
    CREATE OR REPLACE VIEW V_CATALOGO_UNIFICADO AS
    SELECT 
        id_instrumento AS id_origen,    
        nombre_instrumento AS nombre,   
        codigo_instrumento AS codigo,  
        'INSTRUMENTO' AS tipo_material, -- <--- ESTA ES LA CLAVE 
        NULL AS capacidad               
    FROM INSTRUMENTOS
    UNION ALL
    SELECT 
        id_pipeta AS id_origen,         
        nombre_pipeta || ' (' || capacidad || ')' AS nombre, 
        codigo_pipeta AS codigo,
        'PIPETA' AS tipo_material,      -- <--- ESTA ES LA CLAVE 
        capacidad
    FROM MICROPIPETAS
    ORDER BY nombre ASC;

--Insercion de Datos de las tablas Maestras

INSERT INTO INSTRUMENTOS (nombre_instrumento, codigo_instrumento) VALUES ('Cuchara', 'cuchara');
INSERT INTO INSTRUMENTOS (nombre_instrumento, codigo_instrumento) VALUES ('Bisturí', 'bisturi');
INSERT INTO INSTRUMENTOS (nombre_instrumento, codigo_instrumento) VALUES ('Pinzas', 'pinzas');

INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 22-M', '22-M', '1 ML');
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 23-M', '23-M', '1 ML');
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 72-M', '72-M', '1 ML');
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 98-M', '98-M', '1 ML');
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 100-M', '100-M', '1 ML');
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 102-M', '102-M', '1 ML');

-- Capacidad 10 ML
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 32-M', '32-M', '10 ML');
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 75-M', '75-M', '10 ML');
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 94-M', '94-M', '10 ML');
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 103-M', '103-M', '10 ML');
INSERT INTO MICROPIPETAS (nombre_pipeta, codigo_pipeta, capacidad) VALUES ('Pipeta 106-M', '106-M', '10 ML');



INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (1, 'Balanza 74-M', '74-M');
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (2, 'Camara Flujo laminar 8-M', '8-M');
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (3, 'Balanza 6-M', '6-M');
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (4, 'Meson de Transpaso', 'MES-TR');
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (5, 'Balanza 99-M', '99-M');
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (6, 'Balanza 108-M', '108-M');


INSERT INTO MATERIAL_SIEMBRA (id_material_siembra, nombre_material, detalle_medida) VALUES (1, 'Puntas 1 ML', '1 ML');
INSERT INTO MATERIAL_SIEMBRA (id_material_siembra, nombre_material, detalle_medida) VALUES (2, 'Puntas 10ML', '10 ML');
INSERT INTO MATERIAL_SIEMBRA (id_material_siembra, nombre_material, detalle_medida) VALUES (3, 'Placas estériles 57cm2/150mm', '150mm');
INSERT INTO MATERIAL_SIEMBRA (id_material_siembra, nombre_material, detalle_medida) VALUES (4, 'Asas Drigalsky', 'Estándar');
INSERT INTO MATERIAL_SIEMBRA (id_material_siembra, nombre_material, detalle_medida) VALUES (5, 'Blender', 'Unidad');
INSERT INTO MATERIAL_SIEMBRA (id_material_siembra, nombre_material, detalle_medida) VALUES (6, 'Bolsas estériles', 'Unidad');
INSERT INTO MATERIAL_SIEMBRA (id_material_siembra, nombre_material, detalle_medida) VALUES (7, 'Probeta 250 ML', '250 ML');
INSERT INTO MATERIAL_SIEMBRA (id_material_siembra, nombre_material, detalle_medida) VALUES (8, 'Probeta 100 ML', '100 ML');

-- Equipos de Siembra (Agregados a la misma tabla para que estén disponibles)
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (7, 'Baño-5m', '5-M');
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (8, 'Homogenizador 12-m', '12-M');
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (9, 'Cuenta colonias 9-M', '9-M');
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (10, 'Cuenta Colonias 101-m', '101-M');
INSERT INTO EQUIPOS_LAB (id_equipo, nombre_equipo, codigo_equipo) VALUES (11, 'pHmetro 93-m', '93-M');


INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (1, 'AP 0,1 90ml', '90 ml');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (2, 'AP 0,1 99ml', '99 ml');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (3, 'AP 0,1 450ml', '450 ml');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (4, 'AP 0,1 225ml', '225 ml');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (5, 'AP 0,1 500ml', '500 ml');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (6, 'AP 0,1 tubosml', 'Tubos');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (7, 'PBS 450 ml', '450 ml');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (8, 'SPS 225 ml', '225 ml');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (9, 'SPS Tubos', 'Tubos');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (10, 'SPS sa 90ml', '90 ml');
INSERT INTO DILUYENTES (id_diluyente, nombre_diluyente, mililitros) VALUES (11, 'SPS sa tubos', 'Tubos');

INSERT INTO EQUIPOS_INCUBACION (id_incubacion, nombre_equipo, temperatura_ref) VALUES (1, 'Estufa 73-M (35+/-0,5C)', '35+/-0,5C');
INSERT INTO EQUIPOS_INCUBACION (id_incubacion, nombre_equipo, temperatura_ref) VALUES (2, 'Estufa 2-M(35.5+/-0,5C)', '35.5+/-0,5C');

INSERT INTO MAESTRO_CHECKLIST_LIMPIEZA (id_item, nombre_item, def_seleccionado, def_bloqueado) 
VALUES (1, 'Mesón', 1, 1);

INSERT INTO MAESTRO_CHECKLIST_LIMPIEZA (id_item, nombre_item, def_seleccionado, def_bloqueado) 
VALUES (2, 'Stomacher 12-M', 0, 0);

INSERT INTO MAESTRO_CHECKLIST_LIMPIEZA (id_item, nombre_item, def_seleccionado, def_bloqueado) 
VALUES (3, 'Cámara Flujo laminar 8-M', 0, 0);

INSERT INTO MAESTRO_CHECKLIST_LIMPIEZA (id_item, nombre_item, def_seleccionado, def_bloqueado) 
VALUES (4, 'Balanza 74-M/108-M', 0, 0);

INSERT INTO MAESTRO_CHECKLIST_LIMPIEZA (id_item, nombre_item, def_seleccionado, def_bloqueado) 
VALUES (5, 'Balanza 6-M/99-M', 0, 0);

INSERT INTO MAESTRO_CHECKLIST_LIMPIEZA (id_item, nombre_item, def_seleccionado, def_bloqueado) 
VALUES (6, 'Gabinete', 0, 0);

INSERT INTO MAESTRO_CHECKLIST_LIMPIEZA (id_item, nombre_item, def_seleccionado, def_bloqueado) 
VALUES (7, 'Desinfectante en aerosol', 1, 1);


INSERT INTO MAESTRO_TIPOS_ANALISIS (nombre_analisis) VALUES ('Ram');
INSERT INTO MAESTRO_TIPOS_ANALISIS (nombre_analisis) VALUES ('Hongos');
INSERT INTO MAESTRO_TIPOS_ANALISIS (nombre_analisis) VALUES ('Ram Ruso');


INSERT INTO MAESTRO_FORMAS_CALCULO (id_forma, nombre_forma, def_seleccionado) 
VALUES (1, 'Calculadora', 0);

INSERT INTO MAESTRO_FORMAS_CALCULO (id_forma, nombre_forma, def_seleccionado) 
VALUES (2, 'Plantillas Excel (Almacenar)', 0);

INSERT INTO MAESTRO_FORMAS_CALCULO (id_forma, nombre_forma, def_seleccionado) 
VALUES (3, 'Software', 1);


INSERT INTO LUGARES_ALMACENAMIENTO (id_lugar, nombre_lugar, codigo_lugar) VALUES (1, 'Freezer 33-M', 'FR-33M');
INSERT INTO LUGARES_ALMACENAMIENTO (id_lugar, nombre_lugar, codigo_lugar) VALUES (2, 'Refrigerador 33-M', 'RF-33M');
INSERT INTO LUGARES_ALMACENAMIENTO (id_lugar, nombre_lugar, codigo_lugar) VALUES (3, 'Mesón Siembra', 'MES-SIEM');
INSERT INTO LUGARES_ALMACENAMIENTO (id_lugar, nombre_lugar, codigo_lugar) VALUES (4, 'Gabinete sala Transpaso', 'GAB-TRANS');
--------------------------------------------------------

--TABLAS DE LA BASE DE DATOS CENTRAL
CREATE TABLE MUESTRAS_ALI (
    codigo_ali NUMBER(15) NOT NULL, 
    codigo_otros NUMBER(15),
    observaciones_cliente VARCHAR2(4000),
    observaciones_generales VARCHAR2(4000),
    CONSTRAINT PK_muestras_ali PRIMARY KEY (codigo_ali)
);  

-- TABLA PRINCIPAL: Reporte TPA
CREATE TABLE TPA_REPORTE (
    codigo_ali NUMBER(15) NOT NULL,
    id_lugar NUMBER NOT NULL, 
    observaciones_ingreso VARCHAR2(4000),
    estado_actual VARCHAR2(20) DEFAULT 'EN_PROCESO', 
    fecha_cierre TIMESTAMP,
    usuario_cierre VARCHAR2(20),
    observaciones_finales VARCHAR2(4000),
    firma_digital VARCHAR2(100), -- "Sin firma",
    observaciones_generales_analistas VARCHAR(4000),
    
    -- Campos de auditoría
    fecha_ultima_modificacion TIMESTAMP DEFAULT SYSDATE,
    usuario_ultima_modificacion VARCHAR2(20),

    CONSTRAINT PK_tpa_reporte PRIMARY KEY (codigo_ali),
    CONSTRAINT FK_tpa_muestra FOREIGN KEY (codigo_ali) REFERENCES MUESTRAS_ALI(codigo_ali) ON DELETE CASCADE,
    CONSTRAINT FK_tpa_lugar FOREIGN KEY (id_lugar) REFERENCES LUGARES_ALMACENAMIENTO(id_lugar),
    CONSTRAINT FK_tpa_usr_cierre FOREIGN KEY (usuario_cierre) REFERENCES USUARIOS(rut_analista),
    CONSTRAINT FK_tpa_usr_modificacion FOREIGN KEY (usuario_ultima_modificacion) REFERENCES USUARIOS(rut_analista)
);

-- NIVEL 2: SESIÓN DE ANALISTA
CREATE TABLE TPA_ETAPA2_SESION (
    id_sesion NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_ali NUMBER(15) NOT NULL,
    rut_analista VARCHAR2(20) NOT NULL, 
    
    fecha_inicio TIMESTAMP DEFAULT SYSDATE, 
    fecha_termino TIMESTAMP,                
    
    numero_muestras VARCHAR2(50),        
    observaciones_sesion VARCHAR2(4000), 
    retiro_pesado NUMBER(1), 
    CONSTRAINT FK_e2_reporte FOREIGN KEY (codigo_ali) REFERENCES TPA_REPORTE(codigo_ali) ON DELETE CASCADE,
    CONSTRAINT FK_e2_analista FOREIGN KEY (rut_analista) REFERENCES USUARIOS(rut_analista)
);

-- NIVEL 3-A: EQUIPOS SELECCIONADOS
CREATE TABLE TPA_ETAPA2_EQUIPOS (
    id_uso_equipo NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion NUMBER NOT NULL, 
    id_equipo NUMBER NOT NULL, -- FK a EQUIPOS_LAB (Balanzas, etc.)
    
    CONSTRAINT FK_eq2_sesion FOREIGN KEY (id_sesion) REFERENCES TPA_ETAPA2_SESION(id_sesion) ON DELETE CASCADE,
    CONSTRAINT FK_eq2_maestro FOREIGN KEY (id_equipo) REFERENCES EQUIPOS_LAB(id_equipo)
);

-- NIVEL 3-B: MATERIALES (PIPETAS/INSTRUMENTOS)
CREATE TABLE TPA_ETAPA2_MATERIALES (
    id_uso_material NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_sesion NUMBER NOT NULL, 
    tipo_material VARCHAR2(20) NOT NULL, 
    id_pipeta NUMBER,      -- Se llena si tipo es PIPETA
    id_instrumento NUMBER, -- Se llena si tipo es INSTRUMENTO
    codigo_manual VARCHAR2(100), 
    CONSTRAINT FK_mat_sesion FOREIGN KEY (id_sesion) REFERENCES TPA_ETAPA2_SESION(id_sesion) ON DELETE CASCADE,
    CONSTRAINT FK_mat_pipeta FOREIGN KEY (id_pipeta) REFERENCES MICROPIPETAS(id_pipeta),
    CONSTRAINT FK_mat_inst FOREIGN KEY (id_instrumento) REFERENCES INSTRUMENTOS(id_instrumento)
);

-- ETAPA 3: CHECKLIST
CREATE TABLE TPA_ETAPA3_CHECKLIST (
    id_checklist NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_ali NUMBER(15) NOT NULL,
    
    nombre_item VARCHAR2(100),        
    seleccionado NUMBER(1) DEFAULT 0, 
    bloqueado NUMBER(1) DEFAULT 0,    
    
    CONSTRAINT FK_e3_rep FOREIGN KEY (codigo_ali) REFERENCES TPA_REPORTE(codigo_ali) ON DELETE CASCADE
);

-- ETAPA 4: RETIRO
CREATE TABLE TPA_ETAPA4_RETIRO (
    id_retiro NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_ali NUMBER(15) NOT NULL,
    rut_analista VARCHAR2(20) NOT NULL, 
    fecha_retiro TIMESTAMP DEFAULT SYSDATE, 
    accion_realizada VARCHAR2(100),         
    CONSTRAINT FK_e4_rep FOREIGN KEY (codigo_ali) REFERENCES TPA_REPORTE(codigo_ali) ON DELETE CASCADE,
    CONSTRAINT FK_e4_usr FOREIGN KEY (rut_analista) REFERENCES USUARIOS(rut_analista)
);

-- CABECERA SIEMBRA
CREATE TABLE TPA_ETAPA5_SIEMBRA (
    id_siembra NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_ali NUMBER(15) NOT NULL,
    
    observaciones_siembra VARCHAR2(4000), -- [JSON: No venía en tu ejemplo, pero útil]
    otros_equipos_texto VARCHAR2(500),    -- [JSON: otrosEquipos]
    fecha_registro TIMESTAMP DEFAULT SYSDATE,
    
    CONSTRAINT UK_siembra_unica UNIQUE (codigo_ali),
    CONSTRAINT FK_e5_rep FOREIGN KEY (codigo_ali) REFERENCES TPA_REPORTE(codigo_ali) ON DELETE CASCADE
);

-- DETALLE UNIFICADO (Diluyentes, Equipos, Materiales)
CREATE TABLE TPA_ETAPA5_RECURSOS (
    id_recurso_siembra NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_siembra NUMBER NOT NULL,
    categoria_recurso VARCHAR2(20) NOT NULL, -- 'MATERIAL', 'DILUYENTE', 'EQUIPO'
    id_material_siembra NUMBER,
    codigo_material VARCHAR2(100),
    id_diluyente NUMBER,
    id_incubacion NUMBER, 
    codigo_diluyente VARCHAR2(100), 
    seleccionado NUMBER(1) DEFAULT 1,
    CONSTRAINT FK_e5_det_padre FOREIGN KEY (id_siembra) REFERENCES TPA_ETAPA5_SIEMBRA(id_siembra) ON DELETE CASCADE,
    CONSTRAINT FK_e5_mat FOREIGN KEY (id_material_siembra) REFERENCES MATERIAL_SIEMBRA(id_material_siembra),
    CONSTRAINT FK_e5_dil FOREIGN KEY (id_diluyente) REFERENCES DILUYENTES(id_diluyente),
    CONSTRAINT FK_e5_inc FOREIGN KEY (id_incubacion) REFERENCES EQUIPOS_INCUBACION(id_incubacion),
    
    CONSTRAINT CK_e5_cat CHECK (categoria_recurso IN ('MATERIAL', 'DILUYENTE', 'EQUIPO'))
);

--Reporte RAM
--------------------------------------------------------
-- 1. RAM_REPORTE (Consolidado)
--------------------------------------------------------
CREATE TABLE RAM_REPORTE (
    codigo_ali NUMBER(15) NOT NULL,

    -- ETAPA 1
    agar_plate_count VARCHAR2(50),     
    id_equipo_incubacion NUMBER,        
    n_muestra_10gr NUMBER,             
    n_muestra_50gr NUMBER,              
    hora_inicio_homogenizado VARCHAR2(10), 
    hora_termino_siembra VARCHAR2(10),

    -- ETAPA 2
    id_responsable_analisis NUMBER,     
    nombre_responsable_incubacion VARCHAR2(100), 
    fecha_inicio_incubacion DATE,
    fecha_fin_incubacion DATE,
    hora_inicio_incubacion VARCHAR2(10),
    hora_fin_incubacion VARCHAR2(10),
    micropipeta_utilizada VARCHAR2(100),

    -- ETAPA 4 (Lectura) -- ¡AGREGUÉ ESTAS DOS!
    hora_inicio_lectura VARCHAR2(10),   
    hora_fin_lectura VARCHAR2(10),     
    temperatura NUMBER(5, 2),          
    blanco_ufc NUMBER,
    control_ufc NUMBER,
    control_siembra_ecoli NUMBER,
    control_ambiental_pesado NUMBER,
    ufc_final_reporte NUMBER(15, 2),    

    -- ETAPA 5
    desfavorable VARCHAR2(10),
    mercado VARCHAR2(100),
    tabla_pagina VARCHAR2(50),
    limite VARCHAR2(50),
    fecha_entrega DATE,
    hora_entrega VARCHAR2(10),

    -- ETAPA 6
    analisis_nombre VARCHAR2(100),
    control_blanco_val VARCHAR2(50),
    control_blanco_estado VARCHAR2(20),
    control_siembra_val VARCHAR2(50),
    control_siembra_estado VARCHAR2(20),
    duplicado_ali_val VARCHAR2(50),
    duplicado_estado VARCHAR2(20),

    -- ETAPA 7
    observaciones_finales VARCHAR2(4000),
    observaciones_generales_analista_ram VARCHAR2(4000),
    firma_coordinador VARCHAR2(100),
    estado_ram VARCHAR2(20) DEFAULT 'EN_PROCESO',

    CONSTRAINT PK_ram_reporte PRIMARY KEY (codigo_ali),
    CONSTRAINT FK_ram_central FOREIGN KEY (codigo_ali) REFERENCES MUESTRAS_ALI(codigo_ali) ON DELETE CASCADE
);

--------------------------------------------------------
-- 2. RAM_ETAPA3_MUESTRAS (Para el array listaRepeticionesEtapa3)
--------------------------------------------------------
CREATE TABLE RAM_ETAPA3_MUESTRAS (
    id_muestra NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo_ali NUMBER(15) NOT NULL,
    numero_muestra NUMBER(5),            

    -- Datos JSON (Objeto 0 y Objeto 1...)
    dil_1 NUMBER(15, 5),                 
    dil_2 NUMBER(15, 5),                 
    disolucion_1 NUMBER(15, 5),          
    disolucion_2 NUMBER(15, 5),          
    
    c1 NUMBER(10),                      
    c2 NUMBER(10),                       
    c3 NUMBER(10),                      
    c4 NUMBER(10),                      

    -- Resultados Calculados
    resultado_ram NUMBER(15, 2),
    resultado_rpes VARCHAR2(50),

    CONSTRAINT FK_ram3_muestras_padre FOREIGN KEY (codigo_ali) 
        REFERENCES RAM_REPORTE(codigo_ali) ON DELETE CASCADE
);

--------------------------------------------------------
-- 3. RAM_ETAPA3_DUPLICADO (Se extrae del primer objeto del array)
--------------------------------------------------------
CREATE TABLE RAM_ETAPA3_DUPLICADO (
    codigo_ali NUMBER(15) PRIMARY KEY,
    id_muestra_original NUMBER, 

    dil_dup_1 NUMBER(15, 5),            
    dil_dup_2 NUMBER(15, 5),             
    disolucion_dup_1 NUMBER(15, 5),      
    disolucion_dup_2 NUMBER(15, 5),     
    
    c_dup_1 NUMBER(10),                  
    c_dup_2 NUMBER(10),                  
    c_dup_3 NUMBER(10),                 
    c_dup_4 NUMBER(10),                  

    resultado_ram_dup NUMBER(15, 2),
    resultado_rpes_dup VARCHAR2(50),

    CONSTRAINT FK_ram3_dup_reporte FOREIGN KEY (codigo_ali) 
        REFERENCES RAM_REPORTE(codigo_ali) ON DELETE CASCADE,
    CONSTRAINT FK_ram3_dup_ref_muestra FOREIGN KEY (id_muestra_original) 
        REFERENCES RAM_ETAPA3_MUESTRAS(id_muestra)
);


-- ========================================
-- TRIGGERS PARA AUDITORÍA
-- ========================================

-- Trigger para actualizar automáticamente la fecha de última modificación en TPA_REPORTE
CREATE OR REPLACE TRIGGER TRG_TPA_AUDIT
BEFORE UPDATE ON TPA_REPORTE
FOR EACH ROW
BEGIN
    :NEW.fecha_ultima_modificacion := SYSDATE;
END;
/






